services: mongodb
sudo: true
language: node_js
node_js:
- node
git:
  quiet: true
cache: npm
install:
- npm install
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

script:
  - cd app/back-end
  - npm install
  - npm run test

env:
  global:
    - secure: IxFD8YhYZlvBYf+U5zoMRy3gv6lDINiEgqWUkfu9I9s2FmseqCuZLr7n7lkOwHNPcWkZN1jHUj/Kvrn60BxNO39DtapZtpK7YBIg7if1uMa4W/ZBWwJZKRpGayVDVGFPzHZFZhv7gEB8u0cwwuikSFk1erN7bDGTiILDPtZZjCN2TL/vrj2NWJeSErtV7TWATTUtCu8qjkKg4FR8VYs3eGTqic55upc+x7P0myQ3XdFQ+pAdUBRkOH7iJ6e52q2DmQkCfYs3O87/nnMQU5z0I0EHMy1RTkyL/Z+jgkd5wGBSyykhqX3y5T84h8H+KzEBpOc+R/m4ja2FAERqtOe2C+QXQaqoSfPI1CDMSuiLI0GVA2TSJmoYISdA09hk3vRl5w33fL0DxomfeqwrLJQM15O4SWV2hgBAsZLU65XcUMrq/UDPnp7I9xQKjMbGJ6d4mf4XYWSY73eT06YVCsZokKigjjOsh5RrX2eU2C9BEdRs+iIJ3QOgNojutYdIvTIP531hcChkyixNvl7luhwWPXnMGp4JB4yi5h4LsUvZFMzXflpVWhEUsTqgO2dg/k34MQ4ybloXWUiSMwNHSNKzngmyc/doP4ufzux63vcFIpBxG5jOkgOuDzpTwuK5w7Rp5VaZAkmUAnc7FJ8wytTa+s+0keB5ikQhsdxpu5kkIGg=
