services: mongodb
sudo: true
language: node_js
node_js:
- node
git:
  quiet: true
cache: npm
install:
- npm install
before_script:
- sleep 15
- mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
- cd app/back-end
- npm install
- npm run test
after_success:
- bash ./deploy_backend.sh
env:
  global:
    - secure: WVG7g0KGO1+Pun6caSfkn1ihdQwQvAd5GgD6APnvCZJUTWdolwm5LJ2fQXuFMAF2/pA74lj1+vwUOirdfh51Mhmro4TvkCYqiyU8tpygu/1mOdUW083TCXKlYr1mJ4edVpPwZcU+Li3o8l6letzeJD3Rv2+WQFPnXqjDgXVkGegbUQrf7HEso5+xZG2uckpZuYIiM4703Cftjc4fnoI1JU8iNtD2CVv5K72n8sLIZiuWY0lmPI4hi113s7GcNVjCvaJwsbVAdNiY4WO4AKJZtfxVupYodu632YmwrLGFrgT5XANyyAR4iOWMSXIEpqpKNkKe5yqolDUJRk0kFPy+XFklgK7JMIqf4lOZGin4AkMarnwWSd1OkuFPfB+q6SBE7evpTIJ3LOHjxe6KEaJT+oqzCJxCqlZZiuwt0YO9STftLxXChC+Fh1HDZsJubSvOLHcAt4P1Dhe85Jh6UAD4ehpJWbqm6lJt9uhRzM/mlz0bHs8xeztNQxfWbXHV4xUIV7SY7dSJ+6FJZiECznW8nMp2D/coizaqCp2lJDRu10Xo3N6jODRNPE9rWCMB4Wx+Zq8uoZZtaL1yvasbCMNnXKq6qG7V73/2wvb6QUiTdNE8hDGKEPx8o3FRvcv5KB29lNlCniTi2CUJxNWmHXlIFrsIDSqvewWU9lZs2KJz8Mg=
    - secure: PCVbw9m6bl7u6/wo+Xhq2obcUBjp6b+Gty4Qbnl7lvaJNfm8b+8Iu4KpID5mGO07BPsgmPwUNqG6FMMKnBvloOBoDXiFTjEswoj7dyrBtNfoj7pK9fOoIf0/jB1+ZojGUoznQKhLasmUmwZURAvStBtd2bozmYBXOHJn3zbUTE71nUWdw+wtujKIfut4Lcm1v2ms5vHUpMU+mQuCypr0b19eU2qstFHm2k9VxzXJTL6SmYdGq+6ndc51Jq9fcvonVsYSICk8Iui757CmOr9vrIAInYXyiSLRvIrt37DetZKEoGZfni7Cdxsg6M36+BBhaaTNoqTT6PQVLiG/P26IdyGNDADsRvoG6wcxnnDgJ+3jypMUVlmbZPXR/lQwD6GWQSq4G7jm14tRsf1PrqJypas+lXP/kjEeqtKIv003Yk56POOTdfmXAGNILTR2p+Vyv2e2mdIOPRXQ66k44Fhp/qEK48Q5sbH/Wg8RSjHVM2aXygHS1gTvYz0rejyu0BEbstJ9D7kaUFzhq1ioP766LPykqYsCGXFYK2df8kykNTPkrLSShLq/O18IZpbTwn2Et5VePWIHkvvD4Va33sAcKWXfE67vsq2oXPtzldVltrYoVjAMph0rxOC2wDV9rdettb/mIuT52NMa12vGohDVLlnHJsclnRhHJZy6BOI9GxM=